#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Sets the six GitHub Actions secrets that .github/workflows/release.yml needs
# to sign RFGEN44 with Developer ID and notarize it (see docs/SIGNING-SECRETS.md).
# RFGEN44 reuses LP-700-App's Developer ID Application certificate.
#
#   scripts/setup-signing-secrets.sh
#   CERT_SHA1=<sha1> scripts/setup-signing-secrets.sh   # after a renewal, or another cert
#
# Nothing is written to disk except the .p12 you export, which it offers to
# delete at the end. No .env: these values only belong in GitHub.

cd "$(dirname "$0")/.."

CERT_SHA1="${CERT_SHA1:-A59B8647CA9706C6E8CDBB461C9801CF715132C4}"   # LP-700-App's cert
TEAM_ID="Y6FT52BKDA"
P12_DEFAULT="$HOME/Desktop/RFGEN44.p12"
SCRATCH="$(mktemp -d)"
CHECK_KC="$SCRATCH/check.keychain-db"
trap 'security delete-keychain "$CHECK_KC" 2>/dev/null || true; rm -rf "$SCRATCH"' EXIT

[[ "$(uname)" == Darwin ]] || { echo "Run this on the Mac that holds the certificate." >&2; exit 1; }
gh auth status >/dev/null 2>&1 || { echo "Log in to GitHub first: gh auth login" >&2; exit 1; }
REPO="$(gh repo view --json nameWithOwner -q .nameWithOwner)"

# p12_hashes FILE PASSWORD imports the .p12 into a throwaway keychain, as the
# release workflow does, and prints the SHA-1 of each valid codesigning
# identity in it. Fails if the password is wrong.
p12_hashes() {
  security delete-keychain "$CHECK_KC" 2>/dev/null || true
  security create-keychain -p check "$CHECK_KC" >/dev/null 2>&1 || return 1
  security import "$1" -k "$CHECK_KC" -P "$2" -T /usr/bin/codesign >/dev/null 2>&1 || return 1
  security find-identity -v -p codesigning "$CHECK_KC" | awk '/^ *[0-9]+\)/ { print $2 }'
  security delete-keychain "$CHECK_KC" 2>/dev/null || true
}

# check_p12 asks for the exported file and its password; succeeds once they
# yield exactly one identity (the expected one, or one the human accepts).
check_p12() {
  local hashes count
  ask P12_PATH "Path to the .p12 (Enter for $P12_DEFAULT):"
  # Accept drag-and-drop paths: strip quotes, trailing space, '\ ' escapes; expand ~.
  P12_PATH="$(sed -e "s/^[\"']//; s/ *$//; s/[\"']$//; s/\\\\ / /g" <<< "${P12_PATH:-$P12_DEFAULT}")"
  P12_PATH="${P12_PATH/#\~/$HOME}"
  if [[ ! -f "$P12_PATH" ]]; then warn "No file at $P12_PATH"; return 1; fi
  ask_secret MACOS_CERT_PASSWORD "Password you set when exporting it:"
  if ! hashes="$(p12_hashes "$P12_PATH" "$MACOS_CERT_PASSWORD")"; then
    warn "Couldn't import it. Is the password right?"; return 1
  fi
  count="$(grep -c . <<< "$hashes" || true)"
  if [[ "$count" != 1 ]]; then
    warn "Found $count codesigning identities in it; CI needs exactly one."
    note "Export the certificate row itself, so its private key comes along, and only that row."
    return 1
  fi
  if [[ "$hashes" != "$CERT_SHA1" ]]; then
    warn "This is certificate $hashes, not $CERT_SHA1."
    confirm "Use it anyway?" || return 1
  fi
  printf '  %s✓%s certificate %s, password OK\n' "$GREEN" "$RESET" "$hashes"
}

# check_notary asks for the Apple ID + app-specific password and has Apple
# confirm them (notarytool history only reads; it submits nothing).
check_notary() {
  ask NOTARY_APPLE_ID "Apple ID email:"
  ask_secret NOTARY_PASSWORD "App-specific password (xxxx-xxxx-xxxx-xxxx):"
  say "Checking with Apple…"
  if xcrun notarytool history --apple-id "$NOTARY_APPLE_ID" --team-id "$TEAM_ID" \
       --password "$NOTARY_PASSWORD" >/dev/null 2>"$SCRATCH/notary.err"; then
    printf '  %s✓%s Apple accepted the credentials\n' "$GREEN" "$RESET"
    return 0
  fi
  warn "Apple rejected them:"
  note "$(tail -n 3 "$SCRATCH/notary.err")"
  return 1
}

TOTAL_STAGES=5

banner "RFGEN44 release signing secrets → $REPO"

stage "Export the signing certificate"
say "Releases are signed with LP-700-App's Developer ID Application certificate."
say "Export it from your keychain as a .p12 file:"
printf '  %s↗ opening%s Keychain Access\n' "$GREEN" "$RESET"
open -a "Keychain Access" 2>/dev/null || warn "Couldn't open it; find Keychain Access with Spotlight."
step "Sidebar: login. Tab: My Certificates."
step "Several rows read 'Developer ID Application: … ($TEAM_ID)'. Double-click"
say  "  each, open Details, scroll to Fingerprints, and find this SHA-1:"
printf '\n      %s%s%s\n\n' "$BOLD" "$(sed 's/../& /g; s/ $//' <<< "$CERT_SHA1")" "$RESET"
step "Right-click that certificate row (not the key under it) → Export…"
step "File Format: Personal Information Exchange (.p12). Save it as"
say  "  RFGEN44.p12 on your Desktop."
step "Choose a password for the file, then type your Mac login password to allow"
say  "  the export."
note "The next stage checks the whole fingerprint, so a wrong pick gets caught."
pause "Press Enter once the .p12 is saved"

stage "Check the .p12"
say "Importing it into a throwaway keychain, exactly as the release workflow will."
until check_p12; do confirm "Try again?" || exit 1; done
pause

stage "Notary credentials"
say "Apple's notary service needs an Apple ID in team $TEAM_ID and an"
say "app-specific password. LP-700-App's release uses the same pair, so reuse"
say "it if you have it saved. Otherwise create one:"
step "Sign in → Sign-In and Security → App-Specific Passwords → +"
step "Name it 'RFGEN44 notary', create it, and copy the password."
if confirm "Open the Apple Account page to create one?"; then
  open_url "https://appleid.apple.com/account/manage"
fi
until check_notary; do confirm "Try again?" || exit 1; done
pause

stage "Write the GitHub secrets"
say "These go to $REPO → Settings → Secrets and variables → Actions:"
note "MACOS_CERT_P12_BASE64, MACOS_CERT_PASSWORD, KEYCHAIN_PASSWORD,"
note "NOTARY_APPLE_ID, NOTARY_TEAM_ID, NOTARY_PASSWORD"
if [[ -n "$(gh secret list 2>/dev/null)" ]]; then warn "Secrets with these names are replaced."; fi
confirm "Write them now?" || { warn "Nothing written. Re-run when ready."; exit 1; }
set_secret MACOS_CERT_P12_BASE64 "$(base64 -i "$P12_PATH")"
set_secret MACOS_CERT_PASSWORD "$MACOS_CERT_PASSWORD"
set_secret KEYCHAIN_PASSWORD "$(uuidgen)"   # only unlocks CI's throwaway keychain
set_secret NOTARY_APPLE_ID "$NOTARY_APPLE_ID"
set_secret NOTARY_TEAM_ID "$TEAM_ID"
set_secret NOTARY_PASSWORD "$NOTARY_PASSWORD"
pause

stage "Delete the exported .p12"
say "GitHub has the certificate now. The file holds your private key, so it"
say "shouldn't stay on the Desktop. The certificate stays in your keychain."
if confirm "Delete $P12_PATH?"; then
  rm -f "$P12_PATH"
  printf '  %s✓ deleted%s %s\n' "$GREEN" "$RESET" "$P12_PATH"
else
  SKIPPED+=("delete $P12_PATH (it holds your private key)")
fi
pause

finish
say "Cut a release:  git tag vX.Y.Z && git push origin vX.Y.Z"
note "The Release workflow builds, signs, notarizes and publishes the DMG."
printf '\n'
